# Generated by Django 5.2.8 on 2025-11-30 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=100)),
                ('recruitment_group', models.CharField(max_length=10)),
                ('standards_json', models.JSONField(default=list)),
                ('scoring_json', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quota', models.IntegerField()),
                ('korean_grade', models.FloatField()),
                ('korean_percentile', models.IntegerField()),
                ('math_grade', models.FloatField()),
                ('math_percentile', models.IntegerField()),
                ('english_grade', models.IntegerField()),
                ('inquiry_grade', models.FloatField()),
                ('inquiry_percentile', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.departmentadmission')),
            ],
        ),
    ]
