# Generated by Django 5.2.8 on 2025-11-24 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='시도교육청')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='학교명')),
            ],
        ),
        migrations.CreateModel(
            name='StandardDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='기준학과명')),
            ],
        ),
        migrations.CreateModel(
            name='HighSchoolDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학과명')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='highschools.highschool', verbose_name='소속 학교')),
                ('standard_departments', models.ManyToManyField(related_name='high_school_departments', to='highschools.standarddepartment', verbose_name='매핑된 기준학과')),
            ],
            options={
                'unique_together': {('school', 'name')},
            },
        ),
    ]
