# Generated by Django 5.2.8 on 2025-11-28 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('highschools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='대학명')),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='university_logos/', verbose_name='대학 로고')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='계열명 (예: 인문계열)')),
                ('korean_score', models.FloatField(default=0, verbose_name='국어 반영 점수')),
                ('math_score', models.FloatField(default=0, verbose_name='수학 반영 점수')),
                ('inquiry_score', models.FloatField(default=0, verbose_name='탐구 반영 점수')),
                ('english_method', models.CharField(choices=[('ADD', '가산점'), ('SUB', '감점')], default='ADD', max_length=10, verbose_name='영어 반영방식')),
                ('english_grade_points', models.JSONField(blank=True, null=True, verbose_name='영어 등급별 점수표')),
                ('naesin_reflection_score', models.FloatField(default=0, verbose_name='내신 반영 점수')),
                ('eligible_standard_departments', models.ManyToManyField(blank=True, related_name='eligible_divisions', to='highschools.standarddepartment', verbose_name='지원 가능 기준학과')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='universities.university', verbose_name='소속 대학')),
            ],
            options={
                'verbose_name': '모집 계열',
                'verbose_name_plural': '모집 계열 목록',
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UniversityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학과명')),
                ('recruitment_group', models.CharField(choices=[('가군', '가군'), ('나군', '나군'), ('다군', '다군'), ('군외', '군외')], default='가군', max_length=10, verbose_name='모집군')),
                ('korean_score', models.FloatField(blank=True, null=True, verbose_name='국어 점수(예외)')),
                ('math_score', models.FloatField(blank=True, null=True, verbose_name='수학 점수(예외)')),
                ('inquiry_score', models.FloatField(blank=True, null=True, verbose_name='탐구 점수(예외)')),
                ('english_method', models.CharField(blank=True, choices=[('ADD', '가산점'), ('SUB', '감점')], max_length=10, null=True, verbose_name='영어 방식(예외)')),
                ('english_grade_points', models.JSONField(blank=True, null=True, verbose_name='영어 점수표(예외)')),
                ('naesin_reflection_score', models.FloatField(blank=True, null=True, verbose_name='내신 점수(예외)')),
                ('eligible_standard_departments', models.ManyToManyField(blank=True, related_name='eligible_departments', to='highschools.standarddepartment', verbose_name='지원 가능 기준학과 (예외)')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='universities.universitydivision', verbose_name='소속 계열')),
            ],
            options={
                'unique_together': {('division', 'name', 'recruitment_group')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='학년도')),
                ('recruit_count', models.IntegerField(blank=True, null=True, verbose_name='모집인원')),
                ('korean_grade', models.FloatField(blank=True, null=True, verbose_name='국어 등급')),
                ('korean_percentile', models.FloatField(blank=True, null=True, verbose_name='국어 백분위')),
                ('math_grade', models.FloatField(blank=True, null=True, verbose_name='수학 등급')),
                ('math_percentile', models.FloatField(blank=True, null=True, verbose_name='수학 백분위')),
                ('english_grade', models.FloatField(blank=True, null=True, verbose_name='영어 등급')),
                ('inquiry_grade', models.FloatField(blank=True, null=True, verbose_name='탐구 등급')),
                ('inquiry_percentile', models.FloatField(blank=True, null=True, verbose_name='탐구 백분위')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='universities.universitydepartment', verbose_name='학과')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('department', 'year')},
            },
        ),
    ]
