# Generated by Django 5.2.8 on 2025-11-24 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('highschools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='대학명')),
                ('default_korean_ratio', models.IntegerField(default=0, verbose_name='기본 국어 반영비(%)')),
                ('default_math_ratio', models.IntegerField(default=0, verbose_name='기본 수학 반영비(%)')),
                ('default_english_ratio', models.IntegerField(default=0, verbose_name='기본 영어 반영비(%)')),
                ('default_inquiry_ratio', models.IntegerField(default=0, verbose_name='기본 탐구 반영비(%)')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='학과명')),
                ('korean_ratio', models.IntegerField(blank=True, null=True, verbose_name='국어 반영비(예외)')),
                ('math_ratio', models.IntegerField(blank=True, null=True, verbose_name='수학 반영비(예외)')),
                ('english_ratio', models.IntegerField(blank=True, null=True, verbose_name='영어 반영비(예외)')),
                ('inquiry_ratio', models.IntegerField(blank=True, null=True, verbose_name='탐구 반영비(예외)')),
                ('eligible_standard_departments', models.ManyToManyField(related_name='eligible_university_departments', to='highschools.standarddepartment', verbose_name='지원 가능 기준학과')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='universities.university', verbose_name='소속 대학')),
            ],
            options={
                'unique_together': {('university', 'name')},
            },
        ),
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='학년도')),
                ('recruit_count', models.IntegerField(blank=True, null=True, verbose_name='모집인원')),
                ('applicant_count', models.IntegerField(blank=True, null=True, verbose_name='지원인원')),
                ('average_grade', models.FloatField(blank=True, null=True, verbose_name='평균 등급')),
                ('cutoff_grade', models.FloatField(blank=True, null=True, verbose_name='커트라인(최저) 등급')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_results', to='universities.universitydepartment', verbose_name='학과')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('department', 'year')},
            },
        ),
    ]
