# Generated by Django 5.2.8 on 2025-11-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='default_english_grade_points',
            field=models.JSONField(blank=True, help_text='예: {"1": 100, "2": 95, "3": 90}', null=True, verbose_name='기본 영어 등급별 점수표'),
        ),
        migrations.AddField(
            model_name='university',
            name='default_english_method',
            field=models.CharField(choices=[('RATIO', '비율 반영 (%)'), ('ADD', '가산점 (총점 + @)'), ('SUB', '감점 (총점 - @)')], default='RATIO', max_length=10, verbose_name='기본 영어 반영방식'),
        ),
        migrations.AddField(
            model_name='universitydepartment',
            name='english_grade_points',
            field=models.JSONField(blank=True, null=True, verbose_name='영어 등급별 점수표(예외)'),
        ),
        migrations.AddField(
            model_name='universitydepartment',
            name='english_method',
            field=models.CharField(blank=True, choices=[('RATIO', '비율 반영 (%)'), ('ADD', '가산점 (총점 + @)'), ('SUB', '감점 (총점 - @)')], max_length=10, null=True, verbose_name='영어 반영방식(예외)'),
        ),
        migrations.AlterField(
            model_name='admissionresult',
            name='cutoff_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='커트라인 등급'),
        ),
    ]
