# Generated by Django 5.2.8 on 2025-11-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_university_default_english_grade_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universitydepartment',
            name='eligible_standard_departments',
        ),
        migrations.AddField(
            model_name='university',
            name='standard_guide_image',
            field=models.ImageField(blank=True, help_text='기준학과 표가 있는 경우 이미지를 업로드하세요.', null=True, upload_to='university_guides/', verbose_name='기준학과 안내 이미지'),
        ),
        migrations.AddField(
            model_name='university',
            name='standard_guide_text',
            field=models.TextField(blank=True, default='본 대학은 모집단위와 관련된 전문교과를 이수한 경우 지원 가능합니다.\n(자세한 사항은 입학처 모집요강 참조)', help_text='이미지가 없을 경우 표시될 문구입니다.', null=True, verbose_name='기준학과 안내 문구'),
        ),
        migrations.AlterField(
            model_name='university',
            name='default_english_grade_points',
            field=models.JSONField(blank=True, null=True, verbose_name='기본 영어 등급별 점수표'),
        ),
    ]
