# Generated by Django 5.2.8 on 2025-11-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0003_remove_universitydepartment_eligible_standard_departments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionresult',
            name='applicant_count',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='average_grade',
        ),
        migrations.RemoveField(
            model_name='admissionresult',
            name='cutoff_grade',
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='english_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='영어 등급'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='english_percentile',
            field=models.FloatField(blank=True, null=True, verbose_name='영어 백분위'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='inquiry_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='탐구 등급'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='inquiry_percentile',
            field=models.FloatField(blank=True, null=True, verbose_name='탐구 백분위'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='korean_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='국어 등급'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='korean_percentile',
            field=models.FloatField(blank=True, null=True, verbose_name='국어 백분위'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='math_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='수학 등급'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='math_percentile',
            field=models.FloatField(blank=True, null=True, verbose_name='수학 백분위'),
        ),
        migrations.AddField(
            model_name='admissionresult',
            name='total_average_grade',
            field=models.FloatField(blank=True, null=True, verbose_name='전체 평균 등급'),
        ),
        migrations.AlterField(
            model_name='university',
            name='default_english_grade_points',
            field=models.JSONField(blank=True, help_text='예: {"1": 100, "2": 95, ...}', null=True, verbose_name='기본 영어 등급별 점수표'),
        ),
    ]
